apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    ****
      ****: redis
  template:
    metadata:
      ****
        ****: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: ****
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 
